Repository jenkinsci/plot-plugin, pull requests merged in 2025-02, with the labels that each got.

#168 feat(java): Require Jenkins core 2.479.1 and Java 17.
  pom.xml
Labels: dependencies

#167 Upgrade to Jakarta EE 9
  pom.xml
  src/main/java/hudson/plugins/plot/CSVSeries.java
  src/main/java/hudson/plugins/plot/MatrixPlotPublisher.java
  src/main/java/hudson/plugins/plot/Plot.java
  src/main/java/hudson/plugins/plot/PlotAction.java
  src/main/java/hudson/plugins/plot/PlotBuilder.java
  src/main/java/hudson/plugins/plot/PlotCategoryDataset.java
  src/main/java/hudson/plugins/plot/PlotDescriptor.java
  src/main/java/hudson/plugins/plot/PlotPublisher.java
  src/main/java/hudson/plugins/plot/PlotReport.java
  src/main/java/hudson/plugins/plot/PropertiesSeries.java
  src/main/java/hudson/plugins/plot/Series.java
  src/main/java/hudson/plugins/plot/SeriesFactory.java
  src/main/java/hudson/plugins/plot/XMLSeries.java
  src/test/java/hudson/plugins/plot/CSVReaderTest.java
  src/test/java/hudson/plugins/plot/CSVSeriesTest.java
  src/test/java/hudson/plugins/plot/PlotBuildActionTest.java
  src/test/java/hudson/plugins/plot/SeriesFactoryTest.java
  src/test/java/hudson/plugins/plot/SeriesTestCase.java
  src/test/java/hudson/plugins/plot/XMLSeriesTest.java
Labels: feature

#169 [JENKINS-75091] Fix null pointer exception when title is missing
  src/main/java/hudson/plugins/plot/Plot.java
Labels: bug
