Repository jenkinsci/plot-plugin, pull requests merged in 2025-01, with the labels that each got.

#152 Require 2.452.4 and use API plugins
  pom.xml
Labels: chore

#154 Enable checkstyle for Java 11
  pom.xml
Labels: chore

#153 Use recommended format for scm connection fields
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#156 Replace outdated icons with analytics symbol
  src/main/java/hudson/plugins/plot/MatrixPlotAction.java
  src/main/java/hudson/plugins/plot/PlotAction.java
  src/main/resources/hudson/plugins/plot/MatrixPlotAction/index.jelly
  src/main/resources/hudson/plugins/plot/PlotAction/index.jelly
  src/main/resources/hudson/plugins/plot/PlotReport/index.jelly
Labels: bug

#158 Use default pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#159 [JENKINS-75090] Fix horizontal radio button overlap with later element
  src/main/resources/hudson/plugins/plot/AbstractPlotPublisher/config.jelly
  src/main/resources/hudson/plugins/plot/CSVSeries/config.jelly
Labels: bug

#160 Remove changelog from README, link to archived copy
  README.md
Labels: documentation

#161 Format with spotless
  .gitattributes
  CODESTYLE.md
  CONTRIBUTING.md
  checkstyle/checkstyle-suppressions.xml
  checkstyle/checkstyle.xml
  pom.xml
  src/main/java/hudson/plugins/plot/CSVSeries.java
  src/main/java/hudson/plugins/plot/MatrixPlotAction.java
  src/main/java/hudson/plugins/plot/MatrixPlotPublisher.java
  src/main/java/hudson/plugins/plot/Plot.java
  src/main/java/hudson/plugins/plot/PlotAction.java
  src/main/java/hudson/plugins/plot/PlotBuildAction.java
  src/main/java/hudson/plugins/plot/PlotBuilder.java
  src/main/java/hudson/plugins/plot/PlotDescriptor.java
  src/main/java/hudson/plugins/plot/PlotPublisher.java
  src/main/java/hudson/plugins/plot/PlotReport.java
  src/main/java/hudson/plugins/plot/PropertiesSeries.java
  src/main/java/hudson/plugins/plot/Series.java
  src/main/java/hudson/plugins/plot/SeriesFactory.java
  src/main/java/hudson/plugins/plot/XMLSeries.java
  src/test/java/hudson/plugins/plot/CSVReaderTest.java
  src/test/java/hudson/plugins/plot/CSVSeriesTest.java
  src/test/java/hudson/plugins/plot/PlotBuildActionTest.java
  src/test/java/hudson/plugins/plot/PlotBuilderTest.java
  src/test/java/hudson/plugins/plot/PlotTest.java
  src/test/java/hudson/plugins/plot/PropertiesSeriesTest.java
  src/test/java/hudson/plugins/plot/SeriesFactoryTest.java
  src/test/java/hudson/plugins/plot/SeriesTestCase.java
  src/test/java/hudson/plugins/plot/XMLSeriesTest.java
  wiki-backup/PMD_REPORT_PERL.md
Labels: chore

#162 Remove badges from documentation
  README.md
Labels: documentation

#163 Add CODEOWNERS
  .github/CODEOWNERS
Labels: chore
